#DB\ucee4\ub125\uc158 \uc815\ubcf4
#\uadf8\ub9b0\ud50c\ub7fc
greenplum.db.driver=org.postgresql.Driver
greenplum.db.url=jdbc:postgresql://211.189.132.19:9080/ggits
greenplum.db.username=gpadmin
greenplum.db.password=gpadmin

#hive
hive.db.driver=org.apache.hive.jdbc.HiveDriver
hive.db.url=jdbc:hive2://211.189.132.18:10009/ggits
hive.db.username=nifiadmin
hive.db.password=nifi135@$^